### ISSUE TITLE
YouTube watcher multi-tab thing todo

### ISSUE THREAD

**Issue by TangentFoxy** [Guard13007/guard13007.com#30]
- [x] make the overlay bits hideable / see-through / look pretty
- [ ] make it more clear how to use
- [x] make it save what videos were last loaded in local storage
- [ ] make it able to load videos from GET requests
- [ ] make it able to load videos OR webpages
- [ ] make it able to detect youtube urls and load embeds, otherwise load whole pages
- [ ] add a little link for feedback?
- [x] get rid of whatever is causing this to be slightly larger than the browser window, it shouldn't be
